### ISSUE TITLE
modular-multiplicative-inverse NumberFormatException

### ISSUE THREAD

**Issue by lispro06** [topher200/rsa-cryptography#1]
generate-keys function occur issue at calling modular-multiplicative-inverse.

NumberFormatException For input string: "xxx.x" java.lang.NumberFormatException.forInputString (NumberFormatException.java:48)

It can be changed below.

(defn modular-multiplicative-inverse
  "Determines the inverse cooresponding to a given a with respect to modules m.
  Research: http://en.wikipedia.org/wiki/Modular_multiplicative_inverse and
  http://numericalrecipes.blogspot.com/2009/03/modular-multiplicative-inverse.html"
  [a m](let [[x y] %28extended-gcd a m%29]
    %28big-integer %28int %28mod x m%29%29%29))

**Comment by topher200** [comment]
Thanks! I've used your patch to create https://github.com/topher200/rsa-cryptography/commit/c49a5a6f2cf2c30db1d464c02521599c82bd3fb8
